### ISSUE TITLE
Union3 inf likelihood

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/sn_data#3] opened 2024-04-10 19:25 UTC
Hi @cmbant 

I am talking with David @rubind  about this as well.

We were getting inf chi2 both on CAMB / CLASS. He has a modification to the filed that worked with CAMB but I am still getting inf chi2 when running LCDM w/ CLASS

**Comment by cmbant** [comment] 2024-04-10 19:37
Is this using the test_SN branch? (https://github.com/CobayaSampler/cobaya/pull/353)

**Comment by vivianmiranda** [comment] 2024-04-10 19:56
No - I can try that (I was just using the SN Pantheon likelihood and changed the files to Union).

**Comment by cmbant** [comment] 2024-04-12 08:47
test_SN OK, can close this? Would be nice to have confirmation from @rubind that working correctly as intended though.

**Comment by cmbant** [comment] 2024-04-22 08:54
test_SN now merged. Closing assuming OK, please reopen if not

**Closed as completed by cmbant** 2024-04-22 08:54 UTC
